### ISSUE TITLE
How can/does this project tie into Copperhead + Guardian Project + F-droid?

### ISSUE THREAD

**Issue by elimisteve** [mikeperry-tor/mission-improbable#1]
Does it make sense to have Copperhead + these changes + F-droid + Google Play Store, for example? is that too much of a moving target?

https://guardianproject.info/2016/03/28/copperhead-guardian-project-and-f-droid-partner-to-build-open-verifiably-secure-mobile-ecosystem/

**Comment by NoahAndrews** [comment]
An image built using this repo should have all of the things you list.

**Comment by fedor1113** [comment]
Hello!
@elimisteve, this repo is Copperhead + Guardian Project + F-droid + Tor + Signal (hence Google Play Services - unfortunately) and tries to make this system more secure.
As for that being too much - I think you should decide for yourself (you must also understand that even like that some binary blobs are still necessary + unfortunately, it ships with Google Play).
I think this issue can be closed now. ?

**Comment by elimisteve** [comment]
Sounds great @NoahAndrews and @fedor1113; thanks for the clarification!
