### ISSUE TITLE
cpio is a required dependency of super-bootimg

### ISSUE THREAD

**Issue by anoadragon453** [mikeperry-tor/mission-improbable#11]
GNU `cpio` is required by super-bootimg. My distro did not have it installed by default and thus the ./run_all.sh script failed immediately after printing that CopperheadOS was successfully installed.

```
Copperhead successfully installed!
/home/user/Documents/code/android/mission-improbable/angler-nbd91p /home/user/Documents/code/android/mission-improbable
/home/anoa/Documents/code/android/mission-improbable
/usr/bin/mktemp
./bootimg.sh: line 51: cpio: command not found
```

Not sure if you want to list it (not sure how widely installed it usually is), though I don't see the harm.

**Comment by neuhaus** [comment]
Created a PR for this, it's #15
