### ISSUE TITLE
Host SELinux required?

### ISSUE THREAD

**Issue by anoadragon453** [mikeperry-tor/mission-improbable#12]
Upon going through the script I reached the following snag:
```
Gapps delta applied!
We now need sudo to install the OrWall startup script...
chcon: failed to get security context of 'system/bin/svc': Operation not supported
```
After a bit of searching, this error arises when the system does not have SELinux installed/enabled. This system does not have SELinux so it's likely the issue. 

The re-sign.sh script stops [here](https://github.com/mikeperry-tor/mission-improbable/blob/master/re-sign.sh#L41): 
```
sudo chcon --reference=system/bin/svc system/bin/oem-iptables-init.sh
```

Is it possible for the script to check for SELinux support and if not finding it, adjust itself accordingly, or is SELinux required for this install?

**Comment by mikeperry-tor** [comment]
I think that SELinux doesn't have to be enabled or active, but you need the SELinux utilities installed, and you need kernel ext4 support for extended attributes to read the labels, IIRC.

You can try accessing these labels at a lower level with getfattr: https://www.linuxjournal.com/article/7426?page=0,1 but my guess is that might not work either, if you built a kernel without EA support for ext4fs.

**Comment by anoadragon453** [comment]
Working with a fresh Fedora 25 installation.
