### ISSUE TITLE
Add Nexus 5x update support

### ISSUE THREAD

**Issue by neuhaus** [mikeperry-tor/mission-improbable#13]
From what I've read adding support for the Nexus 5x is possible and something that may not even be a lot of work (the Nexus 5x is also supported by CopperheadOS).
I willing to help with this if I can.

What are the missing pieces? Replicate the stuff in `mission-improbable/extras/angler/` for `bullhead`?

I noticed that `mission-improbable/extras/metadata` also refers to angler.

**Comment by mikeperry-tor** [comment]
So step 0 is to download an OTA update for the nexus 5x (from ex: https://builds.copperhead.co/builds/bullhead-ota_update-2016.11.27.21.33.03.zip), and extract it to  see what the updater-script device names look like. Then I would try to use the angler updater-script, but with those device names (since our updates just take full factory images and flash them to devices, so we only need a very simple updater-script that just does that). The metadata file should also be in there, but I don't actually think it is terribly necessary. If it is, please reorg into the angler subdirectory, and add the one for bullhead to a bullhead directory.

After that, have a look at how I modified https://github.com/CopperheadOS/device_huawei_angler/blob/nougat-mr0.5-release/releasetools.py to create https://github.com/mikeperry-tor/mission-improbable/blob/master/extras/angler/convert-factory.py. You should be able to do the same with https://github.com/CopperheadOS/device_lge_bullhead/blob/nougat-mr0.5-release/releasetools.py

**Comment by neuhaus** [comment]
The device names appear to be identical (same prefix `/dev/block/platform/soc.0/f9824900.sdhci/by-name/`).

One thing I notice in the copperhead OTA updater-script is that it 

- first writes the bootloader images to `/dev/block/platform/soc.0/f9824900.sdhci/by-name/...**bak**`, 
- calls `lge_bullhead_update_gpt();`
- flashes the bootloader images again, sans the "bak" suffix. 

Is this something we should do also? It's not done in the Copperhead OTA updater-script for angler.

**Comment by neuhaus** [comment]
I suppose we need a bullhead version of the binary `./extras/blobs/update-binary`?

**Comment by neuhaus** [comment]
There are two bootloader images being flashed after calling `lge_bullhead_recover_gpt()` that are missing from the project:

- `bootloader.imgdata.img` and
- `bootloader.sec.img`

Also `radio.img` is called `radio.modem.img` on bullhead. Is that something that can be ignored?

**Comment by neuhaus** [comment]
I tried to update to `bullhead-nmf26o` with the contribution from @kopatropa 

There were some messages that looked like errors during the update:

<details>
> ...
> /bin/mktemp
> 6303 Blöcke
> libsepol.avtab_read_item: more than one specifier
> libsepol.avtab_read: failed on entry 515 of 7451
> error(s) encountered while parsing configuration
> Could not load policy

> libsepol.policydb_index_others: security:  1 users, 2 roles, 782 types, 0 bools
> libsepol.policydb_index_others: security: 1 sens, 1024 cats
> libsepol.policydb_index_others: security:  63 classes, 7451 rules, 0 cond rules
> libsepol.policydb_index_others: security:  1 users, 2 roles, 782 types, 0 bools
> libsepol.policydb_index_others: security: 1 sens, 1024 cats
> libsepol.policydb_index_others: security:  63 classes, 7451 rules, 0 cond rules
> source type su does not exist: 0,783
> libsepol.policydb_index_others: security:  1 users, 2 roles, 783 types, 0 bools
> libsepol.policydb_index_others: security: 1 sens, 1024 cats
> libsepol.policydb_index_others: security:  63 classes, 7451 rules, 0 cond rules
> libsepol.policydb_index_others: security:  1 users, 2 roles, 783 types, 0 bools
> libsepol.policydb_index_others: security: 1 sens, 1024 cats
> libsepol.policydb_index_others: security:  63 classes, 7451 rules, 0 cond rules
> source type su_device does not exist: 0,784
> libsepol.policydb_index_others: security:  1 users, 2 roles, 784 types, 0 bools
> libsepol.policydb_index_others: security: 1 sens, 1024 cats
> libsepol.policydb_index_others: security:  63 classes, 7451 rules, 0 cond rules
> libsepol.policydb_index_others: security:  1 users, 2 roles, 784 types, 0 bools
> libsepol.policydb_index_others: security: 1 sens, 1024 cats
> libsepol.policydb_index_others: security:  63 classes, 7451 rules, 0 cond rules
> source type su_daemon does not exist: 0,785
> ...
> libsepol.policydb_index_others: security:  63 classes, 7713 rules, 0 cond rules
> libsepol.avtab_read_item: more than one specifier
> libsepol.avtab_read: failed on entry 50 of 7713
> error(s) encountered while parsing configuration
> Could not load policy
> ~/git/other/mission-improbable/helper-repos/super-bootimg/scripts /tmp/tmp.2OA6YulRIS
> /tmp/tmp.2OA6YulRIS
> 1366 Blöcke

</details>
[work in progress]

**Comment by neuhaus** [comment]
Looks like it failed. After doing the adb sideload and then rebooting, the device boots up but it still shows Android 7.0 and the November 6th security patchlevel.

**Comment by CaseyBakey** [comment]
Hi there.

I'm encoutering the exact same issue as @neuhaus. The build is nmf26o, so not working right now.

Btw, thanks anyway for having added the support for N5X update :)

**Comment by mikeperry-tor** [comment]
I am wondering if this and other selinux issues are due to a problem with the libselinux packages in Debian. I used a Fedora 24 VM...

**Comment by CaseyBakey** [comment]
Maybe not libselinux, but libsepol could be the problem, yes. Android M and further use v30+ sepolicy databases. The libsepol from Ubuntu 16.04 can handle v28 or v29, don't remember.

So do you think super-bootimg is the culprit here?

**Comment by neuhaus** [comment]
Are these SELinux errors important? I'm able to install the factory image using Ubuntu 14.04 just fine. It's just the upgrade script that is broken.

**Comment by Patark** [comment]
I'm getting the same error when trying to update using Fedora 25:

> Installing update...
> E:Error in /sideload/package.zip
> (Status 6)
> 
> Installation aborted.

**Comment by CaseyBakey** [comment]
@neuhaus Yeah, these errors are important... You're not flashing anything useful.

I did however manage to get around this issue : I did modify the 3 different sepolicy-inject binaries present in the helper repository super-bootimg.

For that, I did clone the sepolicy-inject from phhusson and modified the Makefile to compile and link against the libsepol from my CopperheadOS build tree (7.1.1). The resulting sepolicy-inject binary was copied over the 3 binaries from helper super-bootimg (sepolicy-inject(-v2) etc).

I did that 'cause I suspected the version of sepolicy databases changed between the sepolicy-inject used by super-bootimg and Android 7.1.1.

Now sepolicy-inject seems to work fine.

However, there are errors during signing (I guess), 'cause the package is refused by my phone. I did for sure copied the keys from my CopperheadOS build tree into the 'keys' folder of mission-improbable.

But it seems super-bootimg is not using these keys while resigning the boot.img (but using verity keys from its own folder).

Any ideas @mikeperry-tor ?

**Comment by kopatropa** [comment]
I'm still successfully upgrading my Nexus 5X using my modifications. I build the update.zip using Debian. However as already pointed out [here](https://github.com/mikeperry-tor/mission-improbable/pull/22#issuecomment-264705792) I'm using a different (obviously more recent) update-binary than the one included in this repository. Any chance this could be the problem?

**Comment by CaseyBakey** [comment]
Thanks for your response @kopatropa, I did try your solution (copying 'device/lge/bullhead/update-binary' from my CopperheadOS 7.1.1 build tree into mission-improbable 'extras/bullhead' folder), still keeping my sepolicy-inject modification (else got errors about sepolicy patching ("Could not load policy"), and still not good.

The final adb sideload was apparently succesful but I got a red boot screen ("system can't be trusted, or may not work" or something like that) on reboot. Seems to bootloop.

I'm going back to my "stock" CopperheadOS for now. I'm pretty sure there is something wrong with the signing keys (particularly with super-bootimg which seems to use its default keys from its directory instead of real keys specified in 'keys' folder).

**Comment by Patark** [comment]
I tried doing the same thing copying the update-binary from the CopperheadOS repo to the extras/bullhead folder. This time it successfully applied the update and boots into the updated system.

I had no sepolicy errors using Fedora 25 (though I did apply the update .zip on an Arch install, as adb on Fedora couldn't find my device).

**Comment by CaseyBakey** [comment]
Ok @Patark so it should work for people with Ubuntu >=16.10, using the same "fix" (copying the new update-binary).

Ubuntu 16.04 is still on libselinuxllibsepol 2.4 so it won't work.

**Comment by CaseyBakey** [comment]
I did try to run the update.sh script on Fedora 25 instead of Ubuntu 16.04 (to have libselinux/libsepol v2.5 for the super-bootimg helper repo) and the result is exactly the same : sepolicy error during patching, and flashing fails.

Any other idea?
