### ISSUE TITLE
Nexus 6P does not boot, stuck on Google logo.

### ISSUE THREAD

**Issue by chrisbensch** [mikeperry-tor/mission-improbable#19]
I've attempted the install from Linux about 8 times and I still cannot get past the Google logo on the post-install boot-up.  The script is stuck at the message "Please reboot phone into system."  Also, tried to boot into recovery, only thing on the screen is the little dead android with the red triangle.

**Comment by BenBaltz** [comment]
What Copperhead image are you using? Does it go all the way through the fastboot flashes?

**Comment by chrisbensch** [comment]
I used the NBD91P image dated 2016.11.27.21.33.03.  Tonight I'll try an older build to see if that helps, I ran out of time earlier.  Do you have a known successful build version?

**Comment by chrisbensch** [comment]
I just attempted with the image dated 2016-11-21 19:25:53, still no luck.  There aren't any errors I can find either.

**Comment by chrisbensch** [comment]
Something I just noticed, it doesn't clean up the old keys if you rerun the setup script.  I cleaned out the old keys, rerunning the setup.

**Comment by chrisbensch** [comment]
After further cleanup (I killed the git repo dir and re-cloned) I noticed the following lines from the terminal output:
libsepol.policydb_index_others: security:  63 classes, 7599 rules, 0 cond rules
libsepol.avtab_read_item: more than one specifier
libsepol.avtab_read: failed on entry 913 of 7599
error(s) encountered while parsing configuration
Could not load policy
/opt/mission-improbable/helper-repos/super-bootimg/scripts /tmp/tmp.92ARG2exMp
Not sure if that helps any.

**Comment by chrisbensch** [comment]
I was running this from Kali linux, decided to load up a fresh Debian 8.  Pretty much the same errors:
libsepol.avtab_read_item: more than one specifier
libsepol.avtab_read: failed on entry 913 of 7599
error(s) encountered while parsing configuration
Could not load policy

**Comment by neuhaus** [comment]
Closely check the output from flash-all.sh. It's easy to overlook failure messages during flashing.

**Comment by chrisbensch** [comment]
I'm getting around to running the steps individually, the first indication of failures are from the "install-su.sh":
/bin/mktemp
6267 blocks
libsepol.avtab_read_item: more than one specifier
libsepol.avtab_read: failed on entry 241 of 7337
error(s) encountered while parsing configuration
Could not load policy
Are these expected?

**Comment by isislovecruft** [comment]
Hi @chrisbensch! This is likely due to your distribution having a different version of `libsepol1`. @mikeperry-tor and I have been using Fedora 24 VMs within QubesOS successfully. I hear that @micahflee successfully ran the build scripts with a newer Debian (stretch, I think?). Please try flashing from Fedora 24 or Debian 9 and reopen if you're still having issues. Thanks!

**Comment by chrisbensch** [comment]
Isis, thank you.  I'll fire up my Qubes and try from there.  Thanks!

**Comment by neuhaus** [comment]
Will Fedora 25 work also?
