### ISSUE TITLE
Great job, although OrWall doesn't work

### ISSUE THREAD

**Issue by tebuevd** [mikeperry-tor/mission-improbable#2]
Been playing around with this for the last 2 days. Very neat and there is definitely huge potential in this. The only issue I've noticed (and it's a major one I guess) is that OrWall completely refuses to work. It simply blocks all traffic and ignores the Tor / Bypass settings for the individual apps that I've set. I didn't update it to 1.2.0 (as per instructions) and I'm pretty sure I did everything else correctly (simply followed run-all.sh, did not enable Transparency Proxy in Orbot).

As it stands, I'm still using the ROM, since I rely on Play Store apps and vanilla Copperhead OS doesn't have it. But everytime the phone starts, I have to manually disable OrWall to be able to use anything at all.

**Comment by mikeperry-tor** [comment]
This could be due to Orbot instability, actually. Orbot unfortunately will often claim it is connected when it really is not. Try killing Orbot from Settings->Apps->Force Stop, and restarting it. Watch the side panel to see if it connects successfully.

If that still doesn't work, enable debugging and do:
adb shell
su
iptables -S
iptables -t nat -S

And then paste that output here or attach it.

**Comment by neuhaus** [comment]
Works for me. All I did was start orWall, start Orbot, then in orWall under "Apps" put the checkbox next to Chromium.

**Comment by tebuevd** [comment]
iptables -S
`-P INPUT DROP
-P FORWARD ACCEPT
-P OUTPUT DROP
-N accounting_IN
-N accounting_OUT
-N bw_FORWARD
-N bw_INPUT
-N bw_OUTPUT
-N bw_costly_rmnet_data0
-N bw_costly_shared
-N bw_data_saver
-N bw_happy_box
-N bw_penalty_box
-N cfw_FORWARD
-N cfw_INPUT
-N cfw_OUTPUT
-N fw_FORWARD
-N fw_INPUT
-N fw_OUTPUT
-N fw_dozable
-N fw_powersave
-N fw_standby
-N natctrl_FORWARD
-N natctrl_tether_counters
-N oem_fwd
-N oem_out
-N orwall_internet
-N orwall_lan
-N st_OUTPUT
-N st_clear_caught
-N st_clear_detect
-N st_penalty_log
-N st_penalty_reject
-N witness
-A INPUT -m owner --uid-owner 10070 -m conntrack --ctstate NEW,RELATED,ESTABLISHED -m comment --comment "Allow Orbot inputs" -j ACCEPT
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -m comment --comment "Allow related,established inputs" -j ACCEPT
-A FORWARD -j oem_fwd
-A FORWARD -j cfw_FORWARD
-A FORWARD -j fw_FORWARD
-A FORWARD -j bw_FORWARD
-A FORWARD -j natctrl_FORWARD
-A OUTPUT -p tcp -m owner --uid-owner 10070 -m tcp --dport 9030 -m comment --comment "Forward Directory traffic to accounting" -j accounting_OUT
-A OUTPUT -m owner --uid-owner 10070 -m conntrack --ctstate NEW,RELATED,ESTABLISHED -m comment --comment "Allow Orbot outputs" -j ACCEPT
-A OUTPUT -d 127.0.0.1/32 -p udp -m owner --uid-owner 0 -m conntrack --ctstate NEW,RELATED,ESTABLISHED -m udp --dport 5400 -m comment --comment "Allow DNS queries" -j ACCEPT
-A OUTPUT -d 127.0.0.1/32 -p tcp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10010 -m tcp --dport 9040 -m comment --comment "Allow com.android.providers.downloads through TransPort" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p udp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10010 -m udp --dport 5400 -m comment --comment "Allow com.android.providers.downloads through DNSProxy" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p tcp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10012 -m tcp --dport 9040 -m comment --comment "Allow com.android.vending through TransPort" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p udp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10012 -m udp --dport 5400 -m comment --comment "Allow com.android.vending through DNSProxy" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p tcp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10014 -m tcp --dport 9040 -m comment --comment "Allow org.fdroid.fdroid through TransPort" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p udp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10014 -m udp --dport 5400 -m comment --comment "Allow org.fdroid.fdroid through DNSProxy" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p tcp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10026 -m tcp --dport 9040 -m comment --comment "Allow com.cyanogenmod.updater through TransPort" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p udp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10026 -m udp --dport 5400 -m comment --comment "Allow com.cyanogenmod.updater through DNSProxy" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p tcp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10029 -m tcp --dport 9040 -m comment --comment "Allow com.google.android.gms through TransPort" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p udp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10029 -m udp --dport 5400 -m comment --comment "Allow com.google.android.gms through DNSProxy" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p tcp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10062 -m tcp --dport 9040 -m comment --comment "Allow org.chromium.chrome through TransPort" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p udp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10062 -m udp --dport 5400 -m comment --comment "Allow org.chromium.chrome through DNSProxy" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p tcp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10073 -m tcp --dport 9040 -m comment --comment "Allow com.fsck.k9 through TransPort" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p udp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10073 -m udp --dport 5400 -m comment --comment "Allow com.fsck.k9 through DNSProxy" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p tcp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10074 -m tcp --dport 9040 -m comment --comment "Allow com.whatsapp through TransPort" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p udp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10074 -m udp --dport 5400 -m comment --comment "Allow com.whatsapp through DNSProxy" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p tcp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10075 -m tcp --dport 9040 -m comment --comment "Allow org.thoughtcrime.securesms through TransPort" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p udp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10075 -m udp --dport 5400 -m comment --comment "Allow org.thoughtcrime.securesms through DNSProxy" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p tcp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10076 -m tcp --dport 9040 -m comment --comment "Allow info.guardianproject.orfox through TransPort" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p udp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10076 -m udp --dport 5400 -m comment --comment "Allow info.guardianproject.orfox through DNSProxy" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p tcp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10077 -m tcp --dport 9040 -m comment --comment "Allow com.google.android.apps.maps through TransPort" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p udp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10077 -m udp --dport 5400 -m comment --comment "Allow com.google.android.apps.maps through DNSProxy" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p tcp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10078 -m tcp --dport 9040 -m comment --comment "Allow com.ubercab through TransPort" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p udp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10078 -m udp --dport 5400 -m comment --comment "Allow com.ubercab through DNSProxy" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p tcp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10079 -m tcp --dport 9040 -m comment --comment "Allow com.andrewshu.android.reddit through TransPort" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p udp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10079 -m udp --dport 5400 -m comment --comment "Allow com.andrewshu.android.reddit through DNSProxy" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p tcp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10080 -m tcp --dport 9040 -m comment --comment "Allow ch.protonmail.android through TransPort" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p udp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10080 -m udp --dport 5400 -m comment --comment "Allow ch.protonmail.android through DNSProxy" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p tcp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10083 -m tcp --dport 9040 -m comment --comment "Allow com.google.android.talk through TransPort" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p udp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10083 -m udp --dport 5400 -m comment --comment "Allow com.google.android.talk through DNSProxy" -j accounting_OUT
-A accounting_IN -j bw_INPUT
-A accounting_IN -j ACCEPT
-A accounting_IN -j bw_INPUT
-A accounting_IN -j ACCEPT
-A accounting_OUT -j bw_OUTPUT
-A accounting_OUT -j ACCEPT
-A accounting_OUT -j bw_OUTPUT
-A accounting_OUT -j ACCEPT
-A bw_FORWARD -o rmnet_data0 -j bw_costly_rmnet_data0
-A bw_INPUT -m quota2 ! --name globalAlert  --quota 2097152 
-A bw_INPUT -i rmnet_data0 -j bw_costly_rmnet_data0
-A bw_INPUT -m owner --socket-exists
-A bw_OUTPUT -m quota2 ! --name globalAlert  --quota 2097152 
-A bw_OUTPUT -o rmnet_data0 -j bw_costly_rmnet_data0
-A bw_OUTPUT -m owner --socket-exists
-A bw_costly_rmnet_data0 -j bw_penalty_box
-A bw_costly_rmnet_data0 -m quota2 ! --name rmnet_data0  --quota 9223372036854775807  -j REJECT --reject-with icmp-port-unreachable
-A bw_costly_shared -j bw_penalty_box
-A bw_data_saver -j RETURN
-A bw_happy_box -m owner --uid-owner 10010 -j RETURN
-A bw_happy_box -m owner --uid-owner 10029 -j RETURN
-A bw_happy_box -m owner --uid-owner 0-9999 -j RETURN
-A bw_happy_box -j bw_data_saver
-A bw_penalty_box -j bw_happy_box
-A cfw_FORWARD -m state --state INVALID -j DROP
-A cfw_INPUT -m state --state INVALID -j DROP
-A cfw_INPUT -p icmp -m icmp --icmp-type 13 -j DROP
-A cfw_OUTPUT -m state --state INVALID -j DROP
-A fw_INPUT -j fw_standby
-A fw_OUTPUT -j fw_standby
-A fw_dozable -p tcp -m tcp --tcp-flags RST RST -j RETURN
-A fw_dozable -m owner --uid-owner 0-9999 -j RETURN
-A fw_dozable -m owner --uid-owner 1001 -j RETURN
-A fw_dozable -m owner --uid-owner 1027 -j RETURN
-A fw_dozable -m owner --uid-owner 10010 -j RETURN
-A fw_dozable -m owner --uid-owner 10024 -j RETURN
-A fw_dozable -m owner --uid-owner 10029 -j RETURN
-A fw_dozable -m owner --uid-owner 10030 -j RETURN
-A fw_dozable -m owner --uid-owner 10070 -j RETURN
-A fw_dozable -m owner --uid-owner 10074 -j RETURN
-A fw_dozable -j DROP
-A fw_powersave -p tcp -m tcp --tcp-flags RST RST -j RETURN
-A fw_powersave -m owner --uid-owner 0-9999 -j RETURN
-A fw_powersave -j DROP
-A fw_standby -p tcp -m tcp --tcp-flags RST RST -j RETURN
-A fw_standby -m owner --uid-owner 10016 -j DROP
-A fw_standby -m owner --uid-owner 10018 -j DROP
-A fw_standby -m owner --uid-owner 10020 -j DROP
-A fw_standby -m owner --uid-owner 10021 -j DROP
-A fw_standby -m owner --uid-owner 10023 -j DROP
-A fw_standby -m owner --uid-owner 10026 -j DROP
-A fw_standby -m owner --uid-owner 10031 -j DROP
-A fw_standby -m owner --uid-owner 10033 -j DROP
-A fw_standby -m owner --uid-owner 10038 -j DROP
-A fw_standby -m owner --uid-owner 10040 -j DROP
-A fw_standby -m owner --uid-owner 10045 -j DROP
-A fw_standby -m owner --uid-owner 10050 -j DROP
-A fw_standby -m owner --uid-owner 10053 -j DROP
-A fw_standby -m owner --uid-owner 10055 -j DROP
-A fw_standby -m owner --uid-owner 10058 -j DROP
-A fw_standby -m owner --uid-owner 10060 -j DROP
-A fw_standby -m owner --uid-owner 10068 -j DROP
-A fw_standby -m owner --uid-owner 10085 -j DROP
-A natctrl_FORWARD -j DROP
-A orwall_internet -d 127.0.0.1/32 -j RETURN
-A orwall_internet -m conntrack --ctstate NEW,RELATED,ESTABLISHED -m owner --uid-owner 10082 -m comment --comment "Allow com.google.android.music to bypass Proxies" -j ACCEPT
-A orwall_internet -d 127.0.0.1/32 -j RETURN
-A orwall_internet -m conntrack --ctstate NEW,RELATED,ESTABLISHED -m owner --uid-owner 10082 -m comment --comment "Allow com.google.android.music to bypass Proxies" -j ACCEPT
-A st_clear_detect -m connmark --mark 0x2000000/0x2000000 -j REJECT --reject-with icmp-port-unreachable
-A st_clear_detect -m connmark --mark 0x1000000/0x1000000 -j RETURN
-A st_clear_detect -p tcp -m u32 --u32 "0x0>>0x16&0x3c@0xc>>0x1a&0x3c@0x0&0xffff0000=0x16030000&&0x0>>0x16&0x3c@0xc>>0x1a&0x3c@0x4&0xff0000=0x10000" -j CONNMARK --set-xmark 0x1000000/0x1000000
-A st_clear_detect -p udp -m u32 --u32 "0x0>>0x16&0x3c@0x8&0xffff0000=0x16fe0000&&0x0>>0x16&0x3c@0x14&0xff0000=0x10000" -j CONNMARK --set-xmark 0x1000000/0x1000000
-A st_clear_detect -m connmark --mark 0x1000000/0x1000000 -j RETURN
-A st_clear_detect -p tcp -m state --state ESTABLISHED -m u32 --u32 "0x0>>0x16&0x3c@0xc>>0x1a&0x3c@0x0&0x0=0x0" -j st_clear_caught
-A st_clear_detect -p udp -j st_clear_caught
-A st_penalty_log -j CONNMARK --set-xmark 0x1000000/0x1000000
-A st_penalty_log -j NFLOG
-A st_penalty_reject -j CONNMARK --set-xmark 0x2000000/0x2000000
-A st_penalty_reject -j NFLOG
-A st_penalty_reject -j REJECT --reject-with icmp-port-unreachable
-A witness -j RETURN
-A witness -j RETURN
`

**Comment by tebuevd** [comment]
iptables -t nat -S

-P INPUT DROP
-P FORWARD ACCEPT
-P OUTPUT DROP
-N accounting_IN
-N accounting_OUT
-N bw_FORWARD
-N bw_INPUT
-N bw_OUTPUT
-N bw_costly_rmnet_data0
-N bw_costly_shared
-N bw_data_saver
-N bw_happy_box
-N bw_penalty_box
-N cfw_FORWARD
-N cfw_INPUT
-N cfw_OUTPUT
-N fw_FORWARD
-N fw_INPUT
-N fw_OUTPUT
-N fw_dozable
-N fw_powersave
-N fw_standby
-N natctrl_FORWARD
-N natctrl_tether_counters
-N oem_fwd
-N oem_out
-N orwall_internet
-N orwall_lan
-N st_OUTPUT
-N st_clear_caught
-N st_clear_detect
-N st_penalty_log
-N st_penalty_reject
-N witness
-A INPUT -m owner --uid-owner 10070 -m conntrack --ctstate NEW,RELATED,ESTABLISHED -m comment --comment "Allow Orbot inputs" -j ACCEPT
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -m comment --comment "Allow related,established inputs" -j ACCEPT
-A FORWARD -j oem_fwd
-A FORWARD -j cfw_FORWARD
-A FORWARD -j fw_FORWARD
-A FORWARD -j bw_FORWARD
-A FORWARD -j natctrl_FORWARD
-A OUTPUT -p tcp -m owner --uid-owner 10070 -m tcp --dport 9030 -m comment --comment "Forward Directory traffic to accounting" -j accounting_OUT
-A OUTPUT -m owner --uid-owner 10070 -m conntrack --ctstate NEW,RELATED,ESTABLISHED -m comment --comment "Allow Orbot outputs" -j ACCEPT
-A OUTPUT -d 127.0.0.1/32 -p udp -m owner --uid-owner 0 -m conntrack --ctstate NEW,RELATED,ESTABLISHED -m udp --dport 5400 -m comment --comment "Allow DNS queries" -j ACCEPT
-A OUTPUT -d 127.0.0.1/32 -p tcp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10010 -m tcp --dport 9040 -m comment --comment "Allow com.android.providers.downloads through TransPort" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p udp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10010 -m udp --dport 5400 -m comment --comment "Allow com.android.providers.downloads through DNSProxy" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p tcp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10012 -m tcp --dport 9040 -m comment --comment "Allow com.android.vending through TransPort" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p udp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10012 -m udp --dport 5400 -m comment --comment "Allow com.android.vending through DNSProxy" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p tcp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10014 -m tcp --dport 9040 -m comment --comment "Allow org.fdroid.fdroid through TransPort" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p udp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10014 -m udp --dport 5400 -m comment --comment "Allow org.fdroid.fdroid through DNSProxy" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p tcp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10026 -m tcp --dport 9040 -m comment --comment "Allow com.cyanogenmod.updater through TransPort" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p udp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10026 -m udp --dport 5400 -m comment --comment "Allow com.cyanogenmod.updater through DNSProxy" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p tcp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10029 -m tcp --dport 9040 -m comment --comment "Allow com.google.android.gms through TransPort" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p udp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10029 -m udp --dport 5400 -m comment --comment "Allow com.google.android.gms through DNSProxy" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p tcp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10062 -m tcp --dport 9040 -m comment --comment "Allow org.chromium.chrome through TransPort" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p udp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10062 -m udp --dport 5400 -m comment --comment "Allow org.chromium.chrome through DNSProxy" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p tcp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10073 -m tcp --dport 9040 -m comment --comment "Allow com.fsck.k9 through TransPort" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p udp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10073 -m udp --dport 5400 -m comment --comment "Allow com.fsck.k9 through DNSProxy" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p tcp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10074 -m tcp --dport 9040 -m comment --comment "Allow com.whatsapp through TransPort" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p udp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10074 -m udp --dport 5400 -m comment --comment "Allow com.whatsapp through DNSProxy" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p tcp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10075 -m tcp --dport 9040 -m comment --comment "Allow org.thoughtcrime.securesms through TransPort" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p udp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10075 -m udp --dport 5400 -m comment --comment "Allow org.thoughtcrime.securesms through DNSProxy" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p tcp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10076 -m tcp --dport 9040 -m comment --comment "Allow info.guardianproject.orfox through TransPort" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p udp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10076 -m udp --dport 5400 -m comment --comment "Allow info.guardianproject.orfox through DNSProxy" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p tcp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10077 -m tcp --dport 9040 -m comment --comment "Allow com.google.android.apps.maps through TransPort" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p udp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10077 -m udp --dport 5400 -m comment --comment "Allow com.google.android.apps.maps through DNSProxy" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p tcp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10078 -m tcp --dport 9040 -m comment --comment "Allow com.ubercab through TransPort" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p udp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10078 -m udp --dport 5400 -m comment --comment "Allow com.ubercab through DNSProxy" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p tcp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10079 -m tcp --dport 9040 -m comment --comment "Allow com.andrewshu.android.reddit through TransPort" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p udp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10079 -m udp --dport 5400 -m comment --comment "Allow com.andrewshu.android.reddit through DNSProxy" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p tcp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10080 -m tcp --dport 9040 -m comment --comment "Allow ch.protonmail.android through TransPort" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p udp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10080 -m udp --dport 5400 -m comment --comment "Allow ch.protonmail.android through DNSProxy" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p tcp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10083 -m tcp --dport 9040 -m comment --comment "Allow com.google.android.talk through TransPort" -j accounting_OUT
-A OUTPUT -d 127.0.0.1/32 -p udp -m conntrack --ctstate NEW,ESTABLISHED -m owner --uid-owner 10083 -m udp --dport 5400 -m comment --comment "Allow com.google.android.talk through DNSProxy" -j accounting_OUT
-A accounting_IN -j bw_INPUT
-A accounting_IN -j ACCEPT
-A accounting_IN -j bw_INPUT
-A accounting_IN -j ACCEPT
-A accounting_OUT -j bw_OUTPUT
-A accounting_OUT -j ACCEPT
-A accounting_OUT -j bw_OUTPUT
-A accounting_OUT -j ACCEPT
-A bw_FORWARD -o rmnet_data0 -j bw_costly_rmnet_data0
-A bw_INPUT -m quota2 ! --name globalAlert  --quota 2097152 
-A bw_INPUT -i rmnet_data0 -j bw_costly_rmnet_data0
-A bw_INPUT -m owner --socket-exists
-A bw_OUTPUT -m quota2 ! --name globalAlert  --quota 2097152 
-A bw_OUTPUT -o rmnet_data0 -j bw_costly_rmnet_data0
-A bw_OUTPUT -m owner --socket-exists
-A bw_costly_rmnet_data0 -j bw_penalty_box
-A bw_costly_rmnet_data0 -m quota2 ! --name rmnet_data0  --quota 9223372036854775807  -j REJECT --reject-with icmp-port-unreachable
-A bw_costly_shared -j bw_penalty_box
-A bw_data_saver -j RETURN
-A bw_happy_box -m owner --uid-owner 10010 -j RETURN
-A bw_happy_box -m owner --uid-owner 10029 -j RETURN
-A bw_happy_box -m owner --uid-owner 0-9999 -j RETURN
-A bw_happy_box -j bw_data_saver
-A bw_penalty_box -j bw_happy_box
-A cfw_FORWARD -m state --state INVALID -j DROP
-A cfw_INPUT -m state --state INVALID -j DROP
-A cfw_INPUT -p icmp -m icmp --icmp-type 13 -j DROP
-A cfw_OUTPUT -m state --state INVALID -j DROP
-A fw_INPUT -j fw_standby
-A fw_OUTPUT -j fw_standby
-A fw_dozable -p tcp -m tcp --tcp-flags RST RST -j RETURN
-A fw_dozable -m owner --uid-owner 0-9999 -j RETURN
-A fw_dozable -m owner --uid-owner 1001 -j RETURN
-A fw_dozable -m owner --uid-owner 1027 -j RETURN
-A fw_dozable -m owner --uid-owner 10010 -j RETURN
-A fw_dozable -m owner --uid-owner 10024 -j RETURN
-A fw_dozable -m owner --uid-owner 10029 -j RETURN
-A fw_dozable -m owner --uid-owner 10030 -j RETURN
-A fw_dozable -m owner --uid-owner 10070 -j RETURN
-A fw_dozable -m owner --uid-owner 10074 -j RETURN
-A fw_dozable -j DROP
-A fw_powersave -p tcp -m tcp --tcp-flags RST RST -j RETURN
-A fw_powersave -m owner --uid-owner 0-9999 -j RETURN
-A fw_powersave -j DROP
-A fw_standby -p tcp -m tcp --tcp-flags RST RST -j RETURN
-A fw_standby -m owner --uid-owner 10016 -j DROP
-A fw_standby -m owner --uid-owner 10018 -j DROP
-A fw_standby -m owner --uid-owner 10020 -j DROP
-A fw_standby -m owner --uid-owner 10021 -j DROP
-A fw_standby -m owner --uid-owner 10023 -j DROP
-A fw_standby -m owner --uid-owner 10026 -j DROP
-A fw_standby -m owner --uid-owner 10031 -j DROP
-A fw_standby -m owner --uid-owner 10033 -j DROP
-A fw_standby -m owner --uid-owner 10038 -j DROP
-A fw_standby -m owner --uid-owner 10040 -j DROP
-A fw_standby -m owner --uid-owner 10045 -j DROP
-A fw_standby -m owner --uid-owner 10050 -j DROP
-A fw_standby -m owner --uid-owner 10053 -j DROP
-A fw_standby -m owner --uid-owner 10055 -j DROP
-A fw_standby -m owner --uid-owner 10058 -j DROP
-A fw_standby -m owner --uid-owner 10060 -j DROP
-A fw_standby -m owner --uid-owner 10068 -j DROP
-A fw_standby -m owner --uid-owner 10085 -j DROP
-A natctrl_FORWARD -j DROP
-A orwall_internet -d 127.0.0.1/32 -j RETURN
-A orwall_internet -m conntrack --ctstate NEW,RELATED,ESTABLISHED -m owner --uid-owner 10082 -m comment --comment "Allow com.google.android.music to bypass Proxies" -j ACCEPT
-A orwall_internet -d 127.0.0.1/32 -j RETURN
-A orwall_internet -m conntrack --ctstate NEW,RELATED,ESTABLISHED -m owner --uid-owner 10082 -m comment --comment "Allow com.google.android.music to bypass Proxies" -j ACCEPT
-A st_clear_detect -m connmark --mark 0x2000000/0x2000000 -j REJECT --reject-with icmp-port-unreachable
-A st_clear_detect -m connmark --mark 0x1000000/0x1000000 -j RETURN
-A st_clear_detect -p tcp -m u32 --u32 "0x0>>0x16&0x3c@0xc>>0x1a&0x3c@0x0&0xffff0000=0x16030000&&0x0>>0x16&0x3c@0xc>>0x1a&0x3c@0x4&0xff0000=0x10000" -j CONNMARK --set-xmark 0x1000000/0x1000000
-A st_clear_detect -p udp -m u32 --u32 "0x0>>0x16&0x3c@0x8&0xffff0000=0x16fe0000&&0x0>>0x16&0x3c@0x14&0xff0000=0x10000" -j CONNMARK --set-xmark 0x1000000/0x1000000
-A st_clear_detect -m connmark --mark 0x1000000/0x1000000 -j RETURN
-A st_clear_detect -p tcp -m state --state ESTABLISHED -m u32 --u32 "0x0>>0x16&0x3c@0xc>>0x1a&0x3c@0x0&0x0=0x0" -j st_clear_caught
-A st_clear_detect -p udp -j st_clear_caught
-A st_penalty_log -j CONNMARK --set-xmark 0x1000000/0x1000000
-A st_penalty_log -j NFLOG
-A st_penalty_reject -j CONNMARK --set-xmark 0x2000000/0x2000000
-A st_penalty_reject -j NFLOG
-A st_penalty_reject -j REJECT --reject-with icmp-port-unreachable
-A witness -j RETURN
-A witness -j RETURN

**Comment by tebuevd** [comment]
Routing via Tor works fine after reseting the Orbot with a Force Stop, but Bypass still doesn't work. Apps configured to bypass simply don't have Internet access.

**Comment by patcon** [comment]
:+1: No biggie, but it's always a little simpler to navigate these issues when big pastes go in a pastebin like gist.github.com :)

**Comment by maertsen** [comment]
I'm seeing similar behaviour on bullhead 2016.12.17.07.29.30; bypass does not seem to work. Orbot crashes frequently. When it does work, sometimes it needs a manual force stop/restart cycle.
Any further pointers / directions to investigate?

**Comment by n3xus5x** [comment]
im having the same issue. bypass not working. also setting up new accounts in conversations constant fail.
and chatsecure says orbot not connected but it is connected O.o

**Comment by isislovecruft** [comment]
Closing, as this is not an issue with these build scripts. If this bug is still happening, please feel free to refile this issue on https://trac.torproject.org (with "Component" set to Orbot) or Orwall's tracker, or mention this issue to @EthACKdotOrg. Thanks!
