### ISSUE TITLE
Multiple Installation Issues

### ISSUE THREAD

**Issue by BobsUncle** [mikeperry-tor/mission-improbable#23]
Hello everyone. 

Just followed the instructions on the git. Device is a Nexus 5x. 

Didn't see any errors. 

The device boots Copperhead. 

Google Play prompts every few seconds saying it has crashed.

I see no other preinstalled apps like Orwall, etc. Just stock + google play icon.

Any help/support would be much appreciated.

**Comment by mikeperry-tor** [comment]
As the install script said, you need to give Google Play Service permissions for Location and Storage (under Settings->Apps->Google Play Services->Permissions).

I'm not sure why the other apps weren't installed. Perhaps you also did not enable debugging as the install script also told you to. You might be able to run just the install-packages.sh again, though. That should work, if you follow its instructions and enable debugging like it says.

**Comment by neuhaus** [comment]
The Google Play thing is mentioned under "INSTALL" at https://blog.torproject.org/blog/mission-improbable-hardening-android-security-and-privacy :

> Once the system is booted, after you have given Google Play Services the Location and Storage permissions (as per the instructions printed by the script), make sure you set the Date and Time accurately, or Orbot will not be able to connect to the Tor Network.
> 
> Then, you can start Orbot, and allow F-Droid, Download Manager, the Copperhead updater, Google Play Services (if you want to use Signal), and any other apps you want to access the network.

**Comment by BobsUncle** [comment]
I am not confident the installation went smoothly at all. I don't see any of the print out or instructions repeatedly referred to throughout the guide. 

I am not an expert with Android. I purchased a Nexus 5X just to follow your protocol. I thought maybe the fact I am running Linux from a VM could be the reason why since I notice VB & VM has intermittent issues with USB devices. 

So, I have gone out and purchased a cheap laptop and have just installed a fresh copy of Ubuntu. 

I am going to follow the instructions again as precisely as I can. I will save everything I do - including installing the pre-requisite files, and other stuff. So you can see all the terminal processes I run through. 

I just used Nexus Root Tool to set my device back to factory. No matter what, OEM Debugging is grayed out I can't select. But I did google the issue and people are saying if device reported unlocked in boot loader then it is safe to ignore. 

Give me an hour and wish me some luck hopefully I get this going smoothly. Will report back soon.

**Comment by BobsUncle** [comment]
Installation did not go smoothly.

None of the apps installed. I had to run the packages script separately. F-droid is not syncing with the repo's. Not sure what I am doing wrong. Here is a copy of all my interactions in terminal from a fresh ubuntu install: 

http://pastebin.com/AzSZjiNu

**Comment by neuhaus** [comment]
There is one issue with fastboot. I had the same issue at first (with Ubuntu 14.04).
See https://github.com/copperhead/bugtracker/issues/498#issuecomment-262506860

Also, you don't have to do everything as root (with sudo).

Instead you can configure udev as described at 
https://developer.android.com/studio/run/device.html

Use `idVendor` `18d1` which is Google.

Regarding the app installation: This is described at https://blog.torproject.org/blog/mission-improbable-hardening-android-security-and-privacy under **Installation: F-Droid apps**: Use `MyAppList` on the phone.

**Comment by BobsUncle** [comment]
Thanks for taking the time to go through this all and post back. I do really appreciate people like yourself who take the time to do such things just to help someone they don't know over the Internet out. 

I am going to follow your instructions and hopefully I can post back some success :)

At the very least, maybe all this can serve as some background should the dev's consider how they can make the guide more stupid friendly :)

**Comment by n3xus5x** [comment]
hi. i just ran this on nexus 5x also many random issues. seemed fine all the way to the end except i manually have to lock and unlock the Boot-loader (fastboot flashing unlock, not works but OEM unlock does)
i used latest copperhead OS image NMF26Q.2016.12.25.22.27.39
phone boots up and setup wizard arrives, connects to WiFi but no network. im assuming its the Orwall Init script issue, mentioned in other posts bug
google services pop up constant, also read allow permission to stop that.. dont need google so i just disabled it.
once devices is booted no apps except for google play added.. (i will manually run packages script and let u know)
also MyAppList isn't in the /sdcard/ folder at all.. im going to re-flash changing a couple things like Orwall 1.1.0 etc.

**Comment by n3xus5x** [comment]
okay ran the package installer and apps installed Perfect. orwall init.d not suported on this device is that normal? other scripts working seems to be a conflict issue if i select apps in orwall then they stop working like fdroid. (tor Enabled in fdroid) if i use Orbot and select apps and untick in orwall then it works O.o
Also the Secure boot ID is 6839-E27F-2CB6
is this correct? its different to the copperheadOs Key
(Nexus 5X fingerprint: 0AA1-7043-4D5F)

Anyways Awesome Prototype !!

**Comment by BobsUncle** [comment]
I have this outstanding issue that is probably unrelated to the scripts provided on this git. When I get to the stage where it reboots and the script tells you to something to the effect "don't forget to give google play services permissions" my computer crashes and restarts. Now this is probable unrelated to the script, and I have no workaround for it. My question is, what scripts should I manually run to make sure I am not missing any settings? So far I just flashed the install-packages.sh. Anything else?

**Comment by isislovecruft** [comment]
It sounds like there were multiple errors in running the script, but that they are now all resolved? Closing, but please feel to reopen if this was in error.
