### ISSUE TITLE
Clock keeps resetting Nexus 6P. Cannot fix. Nothing works. 

### ISSUE THREAD

**Issue by BobsUncle** [mikeperry-tor/mission-improbable#28]
Setup works fine on Nexus 5x. I flashed the 6p. The clock resets after every reboot to 1971.

Disabled Orwall and let network time sync take place.

Rebooted. Phone still clocks back to 1971.

Nothing works because Orbot fails to connect.

I reflashed phone. Installation smooth. But Problem persists!

What should I do to troubleshoot it?

**Comment by BobsUncle** [comment]
The problem was that because the phone was new and had never had a SIM card put in the clock for some reason would not set. As soon as I put a SIM card in the problem resolved itself. So lesson for anyone that purchases a Nexus 6P brand new to setup copperhead - put in a SIM card (does not have to be activated).

**Comment by gcrl** [comment]
I did as you suggested - insert a(n activated, in my case) SIM card - but the clock still resets to 1970 after each reboot, also using a brand new Nexus 6P with a 'mission-improbable setup'. Setting the date and time manually by clicking hundreds of times seems the only solution as far as I know... Is there a simpler way to work around this? Maybe in the terminal? Or a more permanent solution, preferably? Thank you very much for any helpful suggestions.
