### ISSUE TITLE
Not booting on flounder (Nexus 9 WiFi)

### ISSUE THREAD

**Issue by vladimir-lu** [mikeperry-tor/mission-improbable#3]
As per title - it doesn't go past the Google logo when you try the run_all.sh with the flounder image. Am not quite sure how to diagnose the problem either, as there is no logging output anywhere. I suspect it's probably not getting into the bootloader. Maybe something to do with Nexus 9 not having support for verified boot (as is mentioned on the copperhead installation guide). I haven't looked further than this I'm afraid so if nobody wants to investigate then perhaps an addition to the README saying that flounder is known not to work is enough to close this.

**Comment by mikeperry-tor** [comment]
Yeah, I think that's it. You could try to comment out the bits of re-sign.sh that actually append the verity images and boot signatures: https://github.com/mikeperry-tor/mission-improbable/blob/master/re-sign.sh#L53.

You probably also have to remove the calls to BootSignature.jar there, and in the super-bootimg.sh script: https://github.com/mikeperry-tor/super-bootimg/blob/master/scripts/bootimg.sh#L206

That *might* work?

**Comment by neuhaus** [comment]
Can you fix the typo in the title of this issue? It's flounder not flouder.

**Comment by patcon** [comment]
github SEO ftw ;)

**Comment by isislovecruft** [comment]
As mentioned in @patcon's README update, the Nexus 9 WiFi isn't currently supported. If some kind soul would like to undertake supporting it, we're happy to take PRs, but we have neither the time nor resources (nor a Nexus 9 WiFi) to do this ourselves. Sorry.
