### ISSUE TITLE
Mac Randomization doesn't seem to work.

### ISSUE THREAD

**Issue by n3xus5x** [mikeperry-tor/mission-improbable#30]
not sure if linked to mission improbable set up. 

Mac address staying the same
enable disable wifi
reboot
forget networks
setting in Copperhead for Randomization located in settings/more On or Off 
no difference the mac address remains the same. any ideas?

nexus 5x

**Comment by v998** [comment]
see https://github.com/copperhead/bugtracker/issues/147 https://github.com/copperhead/bugtracker/issues/556

**Comment by isislovecruft** [comment]
As noted by @v998, this is possibly a Copperhead OS bug, but is very likely not a bug in these install scripts. Please report your issue to the Copperhead OS developers if you're still experiencing the problem.
