### ISSUE TITLE
Nexus 5x

### ISSUE THREAD

**Issue by orbittheweb** [mikeperry-tor/mission-improbable#33]
Hi , fairly new to the android scene. Tried installing this using linux ubuntu 16.04 on a bullhead nexus 5x (lg). The commands to verify the keys doesnt seem to work ive tried a few things but if im honest ive never had to verify keys before especially within a terminal. Can someone help me out. I tried skipping this step i manage to run the ./run_all.sh script but when i reboot the phone it comes just as normal copperhead would , no google store just f-droid etc.. Im sure im doing something wrong its nothing your end , can someone point me in the right direction.

**Comment by isislovecruft** [comment]
It sounds like part of `run_all.sh` failed somewhere, and perhaps got lost in the terminal background? Also, we only (officially) support using Fedora 24 as the host system for flashing.

> The commands to verify the keys doesnt seem to work ive tried a few things but if im honest ive never had to verify keys before especially within a terminal. Can someone help me out.

It sounds like you're having trouble verifying the Copperhead OS OpenPGP key? I'm not sure what you meant here.

**Comment by isislovecruft** [comment]
It sounds like your issue may be similar to #29 and #31, where other people were also using Linux distros where `python --version` defaults to Python3. This caused a problem in one of the verity key handling scripts, `build_verity_metadata.py`, which would fail silently and the rest of `run_all.sh` would not work correctly.

This should be fixed for you now, @orbittheweb; if not, please feel free to reopen.
