### ISSUE TITLE
adb sideload angler, upgrade 02.07. to 02.12.

### ISSUE THREAD

**Issue by Caesarwm1** [mikeperry-tor/mission-improbable#38]
Hello,

adb sideload (adb 1.0.36, Nexus 6p, Fedora 24 VM) isn't working anymore with Copperhead release N4F26Q.2017.02.07.00.27.27. Tried upgrade to N4F26Q.2017.02.12.02.58.40. With releases (and just days) before, upgrades went more or less smoothly – ./update.sh never worked in one fell swoop. I'm quite sure I didn't miss anything, verifying downloads, keys, usb debugging, etc. 

Qubes' Fedora 24 usb VM gives me:

    [user@sys-usb platform-tools]$ adb sideload 'angler-update-signed.zip'
    Total xfer: 0.00x

Nexus 6p gives me:

    E:can't set up install mounts: no fstab loaded 
    E:failed to set up expected mounts for install: aborting 
    E:unknown volume for path [/cache/recovery/uncrypt_status] 
    Installation aborted 

Or am I facing another problem here? Copperhead says, it's not a Copperhead issue.

Thanks a lot for your attention and your hard work!

**Comment by mikeperry-tor** [comment]
So this is now fixed. The problem was that I didn't specify an ordering on the cpio chunks of the recovery ramdisk while re-signing it. Apparently this didn't matter until 02.07.. or it coincidentally worked out. after 02.07 the lack of ordering began causing etc/recovery.fstab to be clobbered, so nothing would mount in recovery.

Unfortunately, with a broken recovery, there is no way to upgrade. People who hit this bug will have to re-flash :/.

**Comment by Caesarwm1** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

On 03/13/2017 01:01 AM, mikeperry-tor wrote:
> Closed #38.

Thank you for your hard, inspiring work!
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJYxeVoAAoJEMT8xAtQFlSFzS0P/0oZnb0sqXQ+D2jRsgiX5UO6
Ty+T7s7vPHKMzpmLsMCfnzkKaomTe/9g7xHgDKytxuSsD6OUgC4FNrf2xAPeF2KW
9mXEkX089mmHgPb3UPZrwhqKItiqQZouV0zKre7e4XyJcWq2o8M3Pdw1/BtfQ3wd
8cwV6LQImAxVfeMWx4o5DhV4WcFrj5bvkLvgAEZGoRjgFH+iMsagAUoT5LnXzEwx
ZFtKFYh30RCMLroSIkNHOp7kiH2dcMSSLTB5NdGiOSwmizD6WPwPzDAaUusiQ9cB
NFXi7ImdoFBpJpCNd0kHscr48fWxYoIQhWRFUEL0I74tx/39O/b2nSUoC22zN0gl
V3lSH3i2DYIpmO4x+eSwwOddAW1csZee8KYozxETTeuM1TgdDi4tIsGhI7yoJI1o
+8BMt2vt2orzckvKW5ssZ7c61fFUMglqcelUWZTu1hj6B457Zkp5P368H1xlQX3b
gKrv43jvx/FcimObSlCepVjw8cM4wRjuI6i/cN0WyltgHanKBe+65q27h0lvGhVY
Y3h5N/NqpxwovHN6baWr7hniLzn0tWftQi++duH23dRoWo6WId7C7Z45bZgnPltd
sSrIRq5Z5L88I62ACE70EFNVXGloi09nQgrielhigbPbUCmhOqKihoXChaRpDBQM
uwkUWs+wLkwQp1M9x31z
=/Xdq
-----END PGP SIGNATURE-----
